version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    restart: always
    networks:
      - evnet
    volumes:
      - ./models:/app/models   
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: always
    networks:
      - evnet
    volumes:
      - ./models:/app/models   
networks:
  evnet:
    driver: bridge
